#ifndef SP_CONFIGURATION_H_INCLUDED
#define SP_CONFIGURATION_H_INCLUDED


void SP_MENU_OPTION();
void SP_COULEUR_SERPENT(JOUEUR,PARAM_JEU,SNAKE);
void SP_COULEUR_STADE(JOUEUR,PARAM_JEU,SNAKE);
void SP_DIFFICULTE(JOUEUR,PARAM_JEU,SNAKE);
void SP_HAUTEUR_STADE(JOUEUR,PARAM_JEU,SNAKE);
void SP_LARGEUR_STADE(JOUEUR,PARAM_JEU,SNAKE);
void SP_INIT_PARAMETRE_JEU(PARAM_JEU);
void SP_SAUVEGARDE_SCORE(JOUEUR);
void SP_HIGH_SCORE(JOUEUR,PARAM_JEU,SNAKE);
void SP_MENU(JOUEUR,PARAM_JEU,SNAKE);
char * SP_INT_TO_COLOR(int);
void SP_INIT_FICHIER();
void SP_INIT_PARAMETRE_JEU(PARAM_JEU,SNAKE);

#endif // SP_CONFIGURATION_H_INCLUDED
